### ISSUE TITLE
Failed compile 4axis web builder stm32 bluepill 

### ISSUE THREAD

**Issue by FusionHolic** [grblHAL/STM32F1xx#62]
hello terje, i failed to compile stm32 bluepill 4 Axis cnc 3040 using web builder, is bluepill not supported for 4 Axis?

**Comment by terjeio** [comment]
It is, when compiling with STM32CubeIDE.
For some reason the binary generated by the Web Builder (PlatformIO) is quite a bit larger (~4 Kbytes) than the one generated by the STM32CubeIDE - even if the optimization setting is supposedly the same for both.

Since Red/Bluepill support will end at some point it is recommended to switch to a F3xx or F4xx Blackpill instead.
